# Numpy Basic Learning Notes 1

learning reference: https://www.youtube.com/watch?v=GB9ByFAIAH4&t=1426s

This notebook is a showcase of basic concepts of Numpy

other notes:

basic: windows\....\bk4\numpy_test.py

what math can numpy do: this folder\show_numpy_math.ipynb

### 1. Create np array

In [2]:
import numpy as np

In [11]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [12]:
a.dtype


dtype('float64')

-->np.zeors() by defualt is float64, means each number eat 64 bytes in the computer

In [13]:
a = np.ones(5, dtype='int8')
a.dtype

dtype('int8')

In [9]:
np.random.randint(8,10,size = (2,2))


array([[8, 8],
       [8, 8]])

create array of random int bwtween 8 (inclusice) and 10 (exclusive)

create array like identity matrix

In [6]:
np.linspace(0,10,11,endpoint=True)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

endpoint = True 代表含終值,不寫default是True

In [10]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## np.repeat

In [17]:
B = np.array([[[1,2,3],[4,5,6]]])
r3 = np.repeat(B, 2, axis=0)
r4 = np.repeat(B, 2, axis=1)
r5 = np.repeat(B, 2, axis=2)
print("r3\n",r3)
print("r4\n",r4)
print("r5\n",r5)

r3
 [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
r4
 [[[1 2 3]
  [1 2 3]
  [4 5 6]
  [4 5 6]]]
r5
 [[[1 1 2 2 3 3]
  [4 4 5 5 6 6]]]


Explain of np.repeat()

axis是最0代表最外層,愈大number代表愈外層

in array B, 

axis 0 = [[1 2 3] [4 5 6]]the whole thing

axis 1 = [1 2 3] 和 [4 5 6]

axis 2 = 1,2,3,4,5,6


In [24]:
c = np.array([1,2,3,4,5,6,7])
b = np.zeros(3)
c[1:4] = b
print(c)

[1 0 0 0 5 6 7]


## Exercis
create an array that looks like

[1 1 1 1 1 1 1 1 

1 1 1 1 1 1 1 1 

1 1 0 0 0 1 1 1 

1 1 0 9 0 1 1 1 

1 1 0 0 0 1 1 1 

1 1 1 1 1 1 1 1 

1 1 1 1 1 1 1 1 

1 1 1 1 1 1 1 1 ]

In [33]:
#solution
a = np.ones((8,8),dtype='int8')
b = np.zeros((3,3),dtype='int8')
b[1,1] = 9
a[2:5,2:5] = b
print(a)

[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 0 0 0 1 1 1]
 [1 1 0 9 0 1 1 1]
 [1 1 0 0 0 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]


## copying array??


if you say

A = np.array([1,2,3])

B = A

then A and B is pointing to the same array

example


In [34]:
A = np.array([1,2,3])
B = A
B[0] = 9
print(A)
print(B)

[9 2 3]
[9 2 3]


## to make a copy of A, use A.copy()

In [3]:
A = np.array([1,2,3], dtype='float64')
B = A.copy()
B[0] = 9
print(A)
print(B)

[1. 2. 3.]
[9. 2. 3.]


### make a copy of A and change data type using A.astype()

### Reshape array

In [4]:
C = A.astype('int32')
print(C)

[1 2 3]


In [5]:
A = np.array([[1,2,3],[7,8,9]])
B = np.array([4,5,6])
C = np.vstack((A, B))
print(C)

[[1 2 3]
 [7 8 9]
 [4 5 6]]


np.vstack((N1,N2,Nn...))可把array vertically疊起成新的array (形狀需要可以疊起)

In [ ]:
A = np.array([1,2,3,4])
C = np.vstack((A, B))
print(C)  #will give ValueError

In [11]:
A = np.ones((3,2))
B = np.zeros((3,3))
C = np.hstack((A,B))
print(C)

[[1. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0.]]


np.hstack((N1,N2,Nn...))可把array horizontally pack埋成新array (列數需一樣)