# What math can Numpy do?


### 1. perform somthing like matrix-scalar 加減乘除

- Definition: np array ＋—＊／ int or float ==> every element in the array ＋—＊／ the int/float

In [2]:
import numpy as np

In [5]:
A = np.array([1,2,3,4])
A + 2.5

array([3.5, 4.5, 5.5, 6.5])

In [6]:
A * 3

array([ 3,  6,  9, 12])

In [7]:
A = np.array([1,2,3,4])
A + 2.5
print(A)

[1 2 3 4]


In [8]:
A += 2.5
print(A)

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [10]:
A = np.array([1,2,3,4], dtype='float64')
A += 2.5
print(A)

[3.5 4.5 5.5 6.5]


convert raidan to degree

In [15]:
r = np.degrees(np.pi)
print(r)

180.0


### 2. Perform Matrix-Matrix multiplication


In [16]:
A = np.array([[1,0,1],[0,1,0]])
B = np.array([[1,2],[3,4],[5,6]])
AB = np.matmul(A, B)
print(AB)

[[6 8]
 [3 4]]


同數學matrix x matrix一樣

### 3. Obtain determinants

In [19]:
A = np.array([[3,4],[2,1]])
d = np.linalg.det(A)
print(d)


-5.000000000000001


即3X1-4X2


### 4. obtain min max

In [21]:
A = np.array([[3,4,5],[2,1,0]])
print(A.min())
print(A.min(axis = 1))

0
[3 0]


In [26]:
print(A.max(axis = 1))
print(type(A.max()))
print(type(A.max(axis = 1)))
print(type(A))

[5 2]
<class 'numpy.int64'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


### 5. Obtain all elements fiting specific creiteria in the array
e.g. I want to get all elements in the array which >3

In [13]:
A = np.linspace(0,10,11)
#print("A:\n",A)
A>3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True])

Return True/ False regarding the criteria A>3
why this works?

In [19]:
a = np.array((1,2,3,4))
print("1.\n",a[np.array((True,False,True,False))])
print("2.\n",a[np.array((True,True,False,False))])

1.
 [1 3]
2.
 [1 2]


In [10]:
A_largerthan3 = A[A>3]
print(A_largerthan3)
print(type(A_largerthan3))

[ 4.  5.  6.  7.  8.  9. 10.]
<class 'numpy.ndarray'>


get a new array with elements fiting the criteria A>3

### 6. np.any() and np.all()

In [27]:
a0 = np.zeros((1,3))
a1 = np.ones((1,3))
a2 = np.full((1,3),2)
a = np.vstack((a0,a1,a2))
a3 = np.array([[1],[2],[3]])
a = np.hstack((a,a3))
print(a)
print("np.any")
print(np.any(a>1, axis =0))   #return True if at least 1 element in the column >1
print(np.any(a>2, axis =0))
print(np.any(a<3, axis =0))
print("np.all")
print(np.all(a>1, axis =0))  #retuen True if all elements in the column >1
print(np.all(a<3, axis =0))

[[0. 0. 0. 1.]
 [1. 1. 1. 2.]
 [2. 2. 2. 3.]]
np.any
[ True  True  True  True]
[False False False  True]
[ True  True  True  True]
np.all
[False False False False]
[ True  True  True False]


### other functions to be learned
- e.g. find inverse, maybe transpose??