## This py show how to laod .txt to numpy

I have a .txt in same folder

In [2]:
import numpy as np
import os
print("Current working directory: ", os.getcwd())

current working directory:  /home/taliah/jupyter_v1/Learning_notes


In [4]:
file_path = 'array_source_1.txt'
a = np.genfromtxt(file_path, delimiter=',', dtype = 'int32')
print(a)

[[11 12 13 14 15 16]
 [21 22 23 24 25 26]
 [31 32 33 34 35 36]
 [41 42 43 44 45 46]]


put content in array_source_1.txt into numpy array